Complete post section
Ashnaali3255/Portfolio-1 pull request #2
Opened 2022-12-09 20:12 UTC by Ashnaali3255

- Add Images for posts.
- Add titles for posts.
- Add tags for posts.
- Add buttons for posts.
- Add button for resume.
- Add an about us section.
- Add languages.

2022-12-09 21:16 UTC, Ugboaja-Uchechi requested changes
Hi @Ashnaali3255, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

- Linters are passing ✔️ 
- README is descriptive 👍 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-09 21:16 UTC, Ugboaja-Uchechi commented on style.css
> +  }
- [ ] Kindly give your about section a `border` and `border-top-right-radius` as seen in your chosen Figma design 🙏.

Figma Design | Your Design
------------- | -------------
![image](https://user-images.githubusercontent.com/74814780/206796915-5f46fa6a-87ea-4da2-b090-45cc444563cb.png)  |  ![image](https://user-images.githubusercontent.com/74814780/206796857-71fe8bb3-9d89-49b8-ac8a-faf30e5f9f3a.png)

2022-12-09 21:16 UTC, Ugboaja-Uchechi commented on style.css
> +    justify-content: space-between;
- [ ] Kindly align your languages section as close as possible to your chosen Figma design 🙏 

Figma Design | Your Design
------------- | -------------
![image](https://user-images.githubusercontent.com/74814780/206797159-dd13bc89-d07b-4efc-ad32-2310296198c3.png)  |  ![image](https://user-images.githubusercontent.com/74814780/206797204-91446f0e-bd6f-4fa9-9cd8-bb20dd8a958a.png)

2022-12-10 16:57 UTC, Alfredbis29 requested changes
Hi @Ashnaali3255 , 

Good job so far, I can see that you put in a lot of energy into this :+1: 
However, there are some few issues you need to work on in order to proceed to the next project, but believe me, you are almost there. 

 ![soclose](https://user-images.githubusercontent.com/97100091/205930721-3967bc84-4b21-4cec-830a-b6844fe2b36f.gif) 

## Required Changes :recycle: 
Check under the review

## Optional Suggestions
_Check under the review

Cheers and Happy coding :clap: :clap: :clap: 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @alfredbis29  in your question so I can receive the notification.


#### Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

#
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-12-10 16:57 UTC, Alfredbis29 commented on index.html
>    <h3>LET'S CONNECT</h3>
- [ ] kudos for making some changes required in the previous review, but you still need to improve on something but you are almost there, As required for this project, your section uses the font and colors (background and font) defined for the template . kindly fix this for your project to match the Figma design :wink:  don't forget to take care of the background images as displayed on the figma design below :wink: 


Your Design 
![color](https://user-images.githubusercontent.com/88894525/206865084-5eaf2063-9ebd-4d5d-9610-e8573833b258.png)

Figma design
![figmaheader](https://user-images.githubusercontent.com/88894525/206865106-c02bb207-54a2-4575-aacb-f6b41db74ce0.png)

2022-12-10 16:57 UTC, Alfredbis29 commented on index.html
> +      <button>See project</button>
- [ OPTIONAL] As required in the previous review, Kindly make sure your button looks as close as possible :wink: 
Your design
![butti](https://user-images.githubusercontent.com/88894525/206865899-09c75c6f-2932-4cc8-a47f-f9d9a083142c.png)
Figma 
![figmabutti](https://user-images.githubusercontent.com/88894525/206865948-80a3d5bf-4ced-47d2-89f1-cb822adb0085.png)

2022-12-10 20:26 UTC, mckent05 requested changes
Hi @Ashnaali3255,

# STATUS: CHANGES REQUIRED ♻️ ♻️  

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
![almost there](https://user-images.githubusercontent.com/73607512/206874018-81ef0c8e-a6a6-4ba0-9090-628e6b0a52f6.gif)



 ## Highlights
- All linter checks are passing ✔️ 
- You have used the right workflow for this milestone 👏 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your code.


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-10 20:26 UTC, mckent05 commented on index.html
> +  </ul>
- Just as the previous reviewers suggested, please make sure the background images for this section are aligned as it is in the Figma design 🙏. Remember it is important that you try to replicate the Figma design as closely as possible to give confidence to recruiters in your ability to produce exact business requirements 🙏

Your design:
<img width="173" alt="bvsbvhbsbv" src="https://user-images.githubusercontent.com/73607512/206873966-453ea721-b58e-45dc-8274-540042fde241.PNG">

2022-12-10 23:07 UTC, Owusu-Desmond approved these changes
Hi @Ashnaali3255 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media2.giphy.com/media/0C45wbFRJ5Lmf93Kod/giphy.gif"/>

## Highlights
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Great working on the setup of the project ✅
📌 Good commit messages ✅
📌 Professional README file ✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-10 23:09 UTC, merged